<html>
<head>
<title>Green Campus</title>
</head>
<body>
<IMG SRC="sabanci.jpg">
<BR><BR>
<H2>
<?php
$handle = fopen("tempdata.txt", "r");
if ($handle) {
	$zz=fgets($handle);
	$aa=str_getcsv($zz,' ');
	echo " Hourly Temperature(24h) " ;
}
fclose($handle);
?>
</H2>
<BR>
<IMG SRC="graph.php">
<BR><BR>
Graph generated by Halil Alperen EROL
</body>
</html>

